removed unwanted  css
Ansonsd5/basic-component-library pull request #6
Opened 2023-11-05 19:10 UTC by Ansonsd5

2023-11-05 19:28 UTC, jsuryakt requested changes

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +.btn-outline {
We don't need .btn-outline here
.btn-outline should only define border for the button

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +.btn-outline {
Rest of the styles should be similar, btn will not have any border by default
But btn-outline will define a border

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +button[class*="btn"]:active {
Then this should work with .btn
Anyways while using a outlined button user must use it in this way
`<button class="btn btn-outlined">Button</button>`

So btn will be there

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +.btn-outline {
We don't need bg changed with btn-outline doesn't define it

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +.btn-outline {
We can have different classes for colors if reqd

```
<button class="btn btn-secondary">Button</button>
<button class="btn btn-primary">Button</button>
<button class="btn btn-info">Button</button>
<button class="btn btn-warning">Button</button>
```

etc

2023-11-05 19:28 UTC, jsuryakt commented on index.css
> +button[class*="btn"]:disabled {
.btn

2023-11-05 19:28 UTC, jsuryakt commented on index.html
> +    <button class="btn-outline">Button</button>
Re-use the btn class here
`<button class="btn btn-outline">Button</button>`

2023-11-05 19:36 UTC, Ansonsd5 commented on index.css
> +button[class*="btn"]:disabled {
ok

2023-11-06 19:03 UTC, jsuryakt commented on index.css
> +  --transperent-color: #ffffff00;
typo transparent

2023-11-06 19:03 UTC, jsuryakt commented on index.css
> +.btn-outline:active {
.btn-outline not needed here

2023-11-06 19:03 UTC, jsuryakt commented on index.css
> +.btn {
Can add it along with all the .btn styles

2023-11-06 19:03 UTC, jsuryakt commented on index.css
> +.btn-outline:disabled {
can remove btn-outline here

2023-11-06 19:15 UTC, jsuryakt approved these changes
LGTM

2023-11-06 19:15 UTC, merged